import Head from "next/head";
import { useState, useEffect } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { americaCountries } from "@/utils/data";
import SendIcon from "@mui/icons-material/Send";
import ContactPhoneIcon from "@mui/icons-material/ContactPhone";
import { addContact, getContacts, deleteContact, Contact } from "@/utils/db";


export default function Home() {
  const [numberPhone, setNumberPhone] = useState<string>("");
  const [prefijo, setPrefijo] = useState<string>("");
  const [numberComplete, setNumberComplete] = useState<string>("");
  const [nameContact, setNameContact] = useState<string>("");
  const [contacts, setContacts] = useState<Contact[]>([]);
  const [mensaje, setMensaje] = useState<string>('')

  const handleChangePrefijo = (e: React.ChangeEvent<HTMLSelectElement>) => {
    console.log(americaCountries[Number(e.target.value)].prefijo);
    setPrefijo(americaCountries[Number(e.target.value)].prefijo);
  };
  const handleChangePhoneNumber = (e: string) => {
    const onlyNumber = e.replace(/\D/g, "");
    if (prefijo === "") return;
    setNumberPhone(onlyNumber);
  };
  const handleChangeNameContact = (e: string) => {
    setNameContact(e);
  };
  const handleMensaje = (e:string) =>{
    console.log(e)
    setMensaje(e)
  }
  const loadContact = (item: Contact) => {
    setNumberPhone(item.numberPhone);
  };
  useEffect(() => {
    const concatPrefijoNumber: string = prefijo + numberPhone;
    setNumberComplete(concatPrefijoNumber);
  }, [numberPhone, prefijo]);

  useEffect(() => {
    getContacts().then(setContacts);
  }, []);

  const handleAddContact = async () => {
    if (!nameContact || !numberPhone) return;

    await addContact({ nameContact, numberPhone });
    setContacts(await getContacts());

    setNameContact("");
    setNumberComplete("");
  };

  console.log("all contacts: ", contacts);
  const handleDelete = async (id?: number) => {
    if (!id) return;
    await deleteContact(id);
    setContacts(await getContacts());
  };

  const redirectUrls = () => {
    let url: string = `https://wa.me/${numberComplete}?text=${encodeURIComponent(mensaje)}`;;
    window.open(url, "_blank", "noopener,noreferrer");
    return null;
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="manifest" href="/manifest.json" />
         <meta name="theme-color" content="#E70000" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main_body}`}>
        <h1>Go WhatsApp 💬</h1>
        <section className={`${styles.section_form}`}>
          <label className={`${styles.sub_title}`}>Phone Number 🔢📱</label>
          <div className={styles.form_body}>
            <select onChange={handleChangePrefijo}>
              <option>Select</option>
              {americaCountries.map(
                (item: Record<string, string>, index: number) => (
                  <option value={index} className={`${styles.option_select}`}>
                    {item.prefijo} {item.flag}
                  </option>
                )
              )}
            </select>
            <input
              value={numberPhone}
              onChange={(e) => handleChangePhoneNumber(e.target.value)}
              type="number"
              placeholder="phone number"
              className={`${styles.input_number}`}
            />
          </div>
          <textarea value={mensaje} className={`${styles.body_message}`} onChange={(e) => handleMensaje(e.target.value)}></textarea>
          <button
            className={`${styles.button_send}`}
            onClick={() => redirectUrls()}
          >
            Send message <SendIcon className={`${styles.icon_send}`} />
          </button>
        </section>
        <div className={styles.horizontal_line}></div>
        <section className={`${styles.form_save_number}`}>
          <form className={`${styles.form_input_save}`}>
            <input
              className={`${styles.input_save}`}
              value={nameContact}
              onChange={(e) => handleChangeNameContact(e.target.value)}
              type="text"
              placeholder="Name"
            />
            <input
              value={numberComplete}
              className={`${styles.input_save}`}
              placeholder="Phone Number"
              disabled
            />
          </form>
        </section>
        <button
          className={`${styles.button_save}`}
          onClick={() => handleAddContact()}
        >
          Save <ContactPhoneIcon className={`${styles.icon_save}`} />{" "}
        </button>
        <div className={styles.horizontal_line}></div>
        <section className={`${styles.contacts_saved}`}>
          {contacts.map((item: Contact, index: number) => (
            <div
              className={`${styles.card_contact}`}
              onClick={() => loadContact(item)}
            >
              <div className={`${styles.name_contact}`}>
                <span>{item.nameContact}</span>{" "}
                <SendIcon className={`${styles.name_contact_delete}`} />
              </div>
              <button
                className={`${styles.name_contact_delete}`}
                onClick={() => handleDelete(item.id)}
              >
                🗑️
              </button>
            </div>
          ))}
        </section>
      </main>
    </>
  );
}
